#!/usr/bin/env bash
# PolySphere Tech — one-shot performance pass.
# Run from the Laravel project root:   bash perf-fix.sh
# Everything it touches is backed up first. Safe to re-run.

set -uo pipefail

CSS=public/assets/main/css
JS=public/assets/main/js
IMG=public/assets/main/imgs
BK=.perf-backup-$(date +%Y%m%d-%H%M%S)

if [ ! -d "$CSS" ]; then
  echo "✖ Run this from the Laravel project root (public/assets/main/css not found)."
  exit 1
fi

mkdir -p "$BK/css" "$BK/js" "$BK/imgs"
cp "$CSS"/*.css "$BK/css/" 2>/dev/null
cp "$JS/main.js" "$BK/js/" 2>/dev/null
cp "$IMG/logo/logo.png" "$BK/imgs/" 2>/dev/null
cp "$IMG/shapes/shape-11.png" "$BK/imgs/" 2>/dev/null
echo "✔ Backups written to $BK"

SRC_CSS=$(find "$CSS" -maxdepth 1 -name '*.css' ! -name 'bundle.min.css')

# ── 1. Google Fonts: move out of CSS @import (render-blocking chain) ────────
URLS=$(grep -hoE "https://fonts\.googleapis\.com/[^'\") ;]+" $SRC_CSS 2>/dev/null | sort -u)
if [ -n "$URLS" ]; then
  mkdir -p resources/views/partials
  OUT=resources/views/partials/google-fonts.blade.php
  {
    echo "{{-- Generated by perf-fix.sh: non-blocking Google Fonts --}}"
    while IFS= read -r u; do
      case "$u" in *display=*) ;; *) u="$u&display=swap" ;; esac
      echo "<link rel=\"stylesheet\" href=\"$u\" media=\"print\" onload=\"this.media='all'\">"
    done <<< "$URLS"
    echo "<noscript>"
    while IFS= read -r u; do
      case "$u" in *display=*) ;; *) u="$u&display=swap" ;; esac
      echo "    <link rel=\"stylesheet\" href=\"$u\">"
    done <<< "$URLS"
    echo "</noscript>"
  } > "$OUT"
  for f in $SRC_CSS; do
    perl -pi -e 's/\@import\s+(?:url\()?\s*["\x27]?https:\/\/fonts\.googleapis\.com[^;]*;//g' "$f"
  done
  echo "✔ Google Fonts moved to $OUT ($(echo "$URLS" | wc -l | tr -d ' ') stylesheet(s)); @import lines removed"
else
  echo "• No Google Fonts @import found (already done?)"
fi

# ── 2. font-display: swap for Font Awesome / icomoon / any @font-face ──────
for f in $SRC_CSS; do
  perl -0pi -e 's/font-display:\s*block/font-display: swap/g; s/(\@font-face\s*\{)((?:(?!font-display)[^}])*)\}/$1$2;font-display: swap;}/g' "$f"
done
echo "✔ font-display: swap applied to all @font-face rules"

# ── 3. Merge + minify critical CSS into a single file ──────────────────────
if command -v npx >/dev/null 2>&1; then
  if cat "$CSS/bootstrap.min.css" "$CSS/spacing.css" "$CSS/main.css" \
      | npx --yes clean-css-cli -o "$CSS/bundle.min.css" 2>/dev/null && [ -s "$CSS/bundle.min.css" ]; then
    echo "✔ $CSS/bundle.min.css created ($(du -k "$CSS/bundle.min.css" | cut -f1) KB) — layout picks it up automatically"
  else
    rm -f "$CSS/bundle.min.css"
    echo "✖ CSS bundling failed; layout will keep using the three original files"
  fi

  # ── 4. Minify main.js ────────────────────────────────────────────────────
  if npx --yes terser "$JS/main.js" -c -m -o "$JS/main.tmp.js" 2>/dev/null && [ -s "$JS/main.tmp.js" ]; then
    mv "$JS/main.tmp.js" "$JS/main.js"
    echo "✔ main.js minified"
  else
    rm -f "$JS/main.tmp.js"
    echo "✖ main.js minification failed (original untouched)"
  fi
else
  echo "• npx not found — skipped CSS bundle and JS minification (install Node to enable)"
fi

# ── 5. Images (only if ImageMagick / pngquant are installed) ────────────────
IM=$(command -v magick || command -v convert || true)
LOGO="$IMG/logo/logo.png"
if [ -n "$IM" ] && command -v identify >/dev/null 2>&1 && [ -f "$LOGO" ]; then
  w=$(identify -format %w "$LOGO" 2>/dev/null || echo 0)
  if [ "$w" -gt 456 ]; then
    $IM "$LOGO" -resize 456x -strip "$LOGO" && echo "✔ logo.png resized ${w}px → 456px (displayed at 228px, so still 2x sharp)"
  else
    echo "• logo.png already ≤ 456px"
  fi
else
  echo "• ImageMagick not found — resize logo.png to 456px wide manually"
fi
if command -v pngquant >/dev/null 2>&1 && [ -f "$IMG/shapes/shape-11.png" ]; then
  pngquant --force --quality=65-85 --ext .png "$IMG/shapes/shape-11.png" && echo "✔ shape-11.png recompressed"
else
  echo "• pngquant not found — recompress shapes/shape-11.png (47 KiB) via squoosh.app"
fi

echo
echo "Done. Next:"
echo "  1. php artisan view:clear && php artisan cache:clear"
echo "  2. Deploy public/ and resources/views/ to the server (or run this script there)"
echo "  3. Re-run PageSpeed Insights in an incognito window"
